version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8'

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
