version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8:latest'

additional_build_steps:
  prepend: |
    RUN rpm -i https://github.com/getsops/sops/releases/download/v3.8.1/sops-3.8.1.x86_64.rpm && \
      sops -v && \
      mkdir -p /home/runner/.config/sops/age && \
      mkdir -p /home/runner/.config/opn 

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
