version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - dest: configs
    src: ansible.cfg

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
  append_final:
    - RUN rpm -i https://github.com/getsops/sops/releases/download/v3.8.1/sops-3.8.1.x86_64.rpm && sops -v && mkdir -p /home/runner/.config/sops/age && mkdir -p /home/runner/.config/opn 

dependencies:
  galaxy: 
    collections:
      - name: kubernetes.core
      - name: community.sops
      - name: ansible.posix
      - name: community.general
      - name: community.crypto
      - name: amazon.aws
      - name: ansible.controller
      - name: infra.controller_configuration
      - name: infra.aap_utilities
      - name: community.vmware
    roles:
      - name: vcenter_permissions
        src: https://github.com/Vikaspogu/ansible-roles.git
        version: main
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - kubernetes >= 12.0.0
    - httpx
    - proxmoxer
    - requests
    - botocore>=1.19.0
    - boto3>=1.16.0
    - boto>=2.49.0
    - bcrypt
    - jmespath
    - netaddr
    - openshift
    - passlib
    - pyvmomi
    - urllib3
    - PyYAML
    - requests-oauthlib
    - vmware-vcenter
    - vmware-vapi-common-client