version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest'

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
